error_log /dev/stderr;
pid /tmp/nginx.pid;
worker_rlimit_nofile 8192;

events {
  worker_connections 4096; ## Default: 1024
}

http {
  # Service discovery
  server {
    listen 8080;

    root /var/www/html;
    default_type "application/json";
    add_header Content-Type application/json;

    location /service-discover {
      try_files $uri $uri/ /targets.json;
    }
  }

  # Mimir
  upstream mimir_write {
    server mimir-write:9009;
  }
  upstream mimir_read {
    server mimir-read:9009;
  }

  server {
    listen 9009;

    # Push / Ingestion path -> write targets
    location /api/v1/push {
      proxy_pass http://mimir_write;
    }

    # Query / PromQL path -> read targets
    location /prometheus {
      proxy_pass http://mimir_read;
    }
  }

  # Loki
  upstream loki_write {
    server loki-write:3100;
  }

  upstream loki_read {
    server loki-read:3100;
  }

  server {
    listen 3100;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    location = / {
      return 200 'OK';
      auth_basic off;
    }

    location = /api/prom/push {
      proxy_pass http://loki_write;
    }

    location = /api/prom/tail {
      proxy_pass http://loki_read;
    }

    location ~ /api/prom/.* {
      proxy_pass http://loki_read;
    }

    location = /loki/api/v1/push {
      proxy_pass http://loki_write;
    }

    location = /loki/api/v1/tail {
      proxy_pass http://loki_read;
    }

    location ~ /loki/api/.* {