services:
  # --- ALLOY ---
  # Grafana Alloy batches and processes traces sent to it, generating
  # auto-logs from those traces.
  # Includes Metrics, Logs, Traces and Profiles.
  alloy:
    image: grafana/alloy:v1.8.1
    container_name: ${PROJECT_NAME}-alloy
    ports:
      - "12347:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./config/alloy:/etc/alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "--stability.level=experimental",
        "/etc/alloy/config.alloy",
      ]
    networks:
      - kube-devops

  # --- GRAFANA ---
  # The Grafana dashboard
  grafana:
    image: grafana/grafana:11.5.1
    container_name: ${PROJECT_NAME}-grafana
    user: "1000"
    ports:
      - 3000:3000
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app,grafana-pyroscope-app
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWD}
    volumes:
      - ./config/grafana/definitions:/var/lib/grafana/dashboards
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./data/grafana:/var/lib/grafana
    networks:
      - kube-devops

  # --- MIMIR ---
  # mimir:
  #   image: grafana/mimir:2.15.0
  #   command:
  #     [
  #       "-ingester.native-histograms-ingestion-enabled=true",
  #       "-config.file=/etc/mimir.yaml",
  #     ]
  #   ports:
  #     - "9009:9009"
  #   volumes:
  #     - "./mimir/mimir.yaml:/etc/mimir.yaml"

  # --- PROMETHEUS ---
  prometheus:
    container_name: ${PROJECT_NAME}-prometheus
    image: prom/prometheus
    user: "1000"
    command:
      [
        "--log.level=debug",
        "--config.file=/etc/prometheus/prometheus.yaml",
        "--enable-feature=remote-write-receiver",
        "--query.lookback-delta=30s",
      ]
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./data/prometheus:/prometheus
    networks:
      - kube-devops

  # --- LOKI ---
  loki-read:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=read -query-scheduler.use-scheduler-ring=false"
    ports:
      - 3101:3100
      - 7946
      - 9095
    volumes:
      - ./config/loki/loki.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    networks:
      - kube-devops
    healthcheck:
      test: ["CMD", "/usr/bin/loki", "-health"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  loki-write:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=write"
    ports:
      - 3102:3100
      - 7946
      - 9095
    volumes:
      - ./config/loki/loki.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    networks:
      - kube-devops
    healthcheck:
      test: ["CMD", "/usr/bin/loki", "-health"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  loki-backend:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    ports:
      - "3100"
      - "7946"
    volumes:
      - ./config/loki/loki.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
      - nginx
    networks:
      - kube-devops
    healthcheck:
      test: ["CMD", "/usr/bin/loki", "-health"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  # --- NGINX ---
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:latest
    volumes:
      - ./config/nginx/infra-nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/html:/var/www/html
    ports:
      - "3100:3100"
      - "8080:8080"
    networks:
      - kube-devops
    depends_on:
      - loki-read
      - loki-write
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- TEMPO ---
  # tempo:
  #   image: grafana/tempo:2.5.0
  #   container_name: ${PROJECT_NAME}-tempo
  #   command: ["-config.file=/etc/tempo.yaml"]
  #   volumes:
  #     - ./config/tempo.yaml:/etc/tempo.yaml:ro
  #     - ./data/tempo:/var/tmp/tempo
  #   ports:
  #     - "3200:3200"
  #   networks:
  #     - kube-devops

  # --- MINIO (S3 Compatible Storage) ---
  minio:
    image: minio/minio
    user: "1000"
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server --address "0.0.0.0:9000" --console-address "0.0.0.0:9001" /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    networks:
      - kube-devops

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- NODE_EXPORTER ---
  # node-exporter:
  #   image: prom/node-exporter:v1.8.2
  #   container_name: ${PROJECT_NAME}-node-exporter
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - "--path.procfs=/host/proc"
  #     - "--path.sysfs=/host/sys"
  #     - "--path.rootfs=/rootfs"
  #   networks:
  #     - kube-devops
  #   ports:
  #     - "9100:9100"

  # --- LOG GENERATOR ---
  # for testing purposes only, disable in production
  # flog:
  #   image: mingrammer/flog
  #   command: -f json -d 200ms -l
  #   networks:
  #     - kube-devops

  # --- TEMPLATE APPS ---

  # --- API ---
  # api:
  #   container_name: ${PROJECT_NAME}-api
  #   env_file:
  #     - ./api/.env
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./api:/app
  #   ports:
  #     - "${API_PORT}:${API_PORT}"
  #   networks:
  #     - kube-devops

  # --- FRONTEND ---
  # frontend:
  #   container_name: ${PROJECT_NAME}-frontend
  #   env_file:
  #     - ./www/.env
  #   build:
  #     context: ./www
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./www:/app
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  #   networks:
  #     - kube-devops
  #   depends_on:
  #     - api

  # --- POSTGRESQL ---
  # postgres:
  #   container_name: ${PROJECT_NAME}-postgres
  #   image: postgres:17
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./data/psql:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   networks:
  #     - kube-devops

networks:
  kube-devops:
    name: ${PROJECT_NAME}
    driver: bridge
