upstream api {
        server 127.0.0.1:31700;
}

upstream frontend {
        server 127.0.0.1:31701;
}

server {
	server_name api.example.com;
        listen [::]:80;
        listen 80;

	location / {
		proxy_pass http://api;
                include /etc/nginx/proxy_params;
                proxy_redirect off;
	}

}


server {
	server_name app.example.com;
        listen [::]:80;
        listen 80;

	location / {
		proxy_pass http://frontend;
                include /etc/nginx/proxy_params;
                proxy_redirect off;
	}

}
